// <auto-generated />
using System;
using FantasyFb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FantasyFb.Migrations
{
    [DbContext(typeof(FantasyFbContext))]
    partial class FantasyFbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("FantasyFb.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<string>("QB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("K")
                        .HasColumnType("INTEGER");

                    b.Property<string>("D_ST")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
